### ISSUE TITLE
Dynamic wallpapers not created when soft link in path.

### ISSUE THREAD

**Issue by markusgod** [dusansimic/dynamic-wallpaper#54]
Opensuse Tumbleweed gnome 43.0
Installed from Flatpak 0.0.4
App fails to create wallpaper when symlink is in the path.

![image](https://user-images.githubusercontent.com/20001291/196650469-cbbf6561-babe-4481-bdfe-9733f7690760.png)

https://user-images.githubusercontent.com/20001291/196650623-e03baca5-9d1c-4295-92d6-c2c62c70158e.mp4

**Comment by dusansimic** [comment]
Could you please run the app through the terminal (if you're running a flatpak you should be able to to it by running `flatpak run me.dusansimic.DynamicWallpaper`) and paste the logs here. I can't replicate this behavior on my machine.

**Comment by markusgod** [comment]
Stacktrace, when I', trying to open a file.
```
Traceback (most recent call last):
  File "/app/share/me.dusansimic.DynamicWallpaper/dynamic_wallpaper/wallpaper_picker.py", line 76, in _on_wallpaper_chooser_response
    self._update_action_row_labels()
  File "/app/share/me.dusansimic.DynamicWallpaper/dynamic_wallpaper/wallpaper_picker.py", line 59, in _update_action_row_labels
    size = os.path.getsize(self.wallpaper.path)
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/mark/Pictures/Backgrounds/Dynamic_Wallpapers/Adwaita/adwaita-night.jpg'


```

**Comment by dusansimic** [comment]
This will most likely get fixed in the next release
